# Generated by Django 4.2.27 on 2025-12-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: Upload an image/icon for this course', null=True, upload_to='courses/icons/'),
        ),
    ]
