# Generated by Django 4.2.27 on 2025-12-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_duration_course_fee_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(max_length=200),
        ),
    ]
